
CREATE DATABASE database_used;
CREATE TABLE OWNER
(
OwnerID VARCHAR(3),
OwnerUsername VARCHAR(20),
OwnerFName VARCHAR(20),
OwnerLName VARCHAR(20),
OwnerPass VARCHAR(20),
OwnerContact VARCHAR(10),
OwnerAddress VARCHAR(20),
PRIMARY KEY(OwnerID)
);

CREATE TABLE TENANT
(
TenantID VARCHAR(3),
TenantUsername VARCHAR(20),
TenantFName VARCHAR(20),
TenantLName VARCHAR(20),
TenantPass VARCHAR(20),
TenantContact VARCHAR(10),
TenantAddress VARCHAR(20),
PRIMARY KEY(TenantID)
);

CREATE TABLE BUILDING
(
BuildingID VARCHAR(3),
OwnerID VARCHAR(3),
BuildingAddress VARCHAR(25),
BuildingName VARCHAR(20),
BuildingFloors INTEGER(3),
Tenants INTEGER(3),
PRIMARY KEY(BuildingID),
FOREIGN KEY(OwnerID) REFERENCES OWNER(OwnerID) ON DELETE CASCADE
);


CREATE TABLE APARTMENT
(
ApartmentID VARCHAR(3),
FlatNum VARCHAR(10),
BuildingID VARCHAR(3),
TenantID VARCHAR(3),
Rent INTEGER(10),
StartDate DATE,
Owe INTEGER(10),

PRIMARY KEY(ApartmentID),
FOREIGN KEY(BuildingID) REFERENCES BUILDING(BuildingID) ON DELETE CASCADE,
FOREIGN KEY(TenantID) REFERENCES TENANT(TenantID) ON DELETE CASCADE
);


CREATE TABLE PAYMENT
(
PaymentID VARCHAR(3),
PaymentDate DATE,
ApartmentID VARCHAR(3),
TenantID VARCHAR(3),
FlatNum VARCHAR(10),
PaidRent INTEGER(10),

PRIMARY KEY(PaymentID),
FOREIGN KEY(ApartmentID) REFERENCES APARTMENT(ApartmentID) ON DELETE CASCADE,
FOREIGN KEY(TenantID) REFERENCES TENANT(TenantID) ON DELETE CASCADE
);

